include "application.conf"

play.http.secret.key = ${APP_SECRET}

chat.persistence.external = true

play.evolutions.db.default.enabled = true
play.evolutions.db.default.autoApply = false

play.filters.hosts.allowed = ${?ALLOWED_HOSTS}
play.filters.cors.allowedOrigins = ${?CORS_ALLOWED_ORIGINS}
