play.http.secret.key = "todo-async-secret-key"

play.filters.hosts {
  allowed = ["localhost", "localhost:9000", "127.0.0.1", "127.0.0.1:9000"]
}

play.filters.disabled += "play.filters.csrf.CSRFFilter"

# Dispatcher cho blocking I/O
# In-memory store vẫn nhanh, nhưng giả lập như thật để benchmark chính xác
blocking-io-dispatcher {
  type = Dispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    fixed-pool-size = 30
  }
  throughput = 1
}
